### ISSUE TITLE
Problems Running Code

### ISSUE THREAD

**Issue by baileyheit** [ulfaslak/caobd_f19#11]
I am having trouble with running the code. I have attempted to run their code in many settings with many different networks for at least 30 minutes, once for an hour. I have been able to run my own code for these problems. I am unable to view the histograms or anything in week 3 and there is no markdown that helps infer results. 

How can I fix this or find another way to grade them?

**Comment by ulfaslak** [comment]
This is a bit late, but for next time: You don't need to verify that their code runs. If the output seems genuine, then the code probably ran on their computers. Since I don't know what error you are getting I can't be more specific than this. But if the error was a FileNotFoundError then it's because the data directory on your computer is in a different place relative to the script than it was on their computer, which is not their fault. Also there may be be other errors due to different formatting of the data, etc.. Therefore I can't require that reviewers should be able to run the code they are reviewing.
