### ISSUE TITLE
Ex. 2.2.4 Plotting Covariance Matrix

### ISSUE THREAD

**Issue by sidswear** [ulfaslak/caobd_f19#3]
For the question where we are asked to find the covariance matrix for the "news" and "blackmirror" forums, I was able to make the covariance matrix, but when I tried to plot the histogram nothing showed up. 
Is this a network error or an issue with the code? Is there any way to make it run more smoothly if it is a network error?
<img width="720" alt="Screen Shot 2019-09-19 at 3 22 26 PM" src="https://user-images.githubusercontent.com/55449037/65247841-6819b700-daf1-11e9-84b7-f5d89e257b65.png">

**Comment by ulfaslak** [comment]
The covariance matrix is a square (N x N dimensional) array. The `plt.hist` function takes as input a one dimensional array (list of numbers), so when inputting the cov. matrix it simply doesn't work. Worse even, it seems that it actually *tries* to do something (probably plot one histogram for each row), and that's taking a lot of time which is why you have the little asterix left of the cell indicating that it's still running.

SO. The covariance matrix is, as I said, an N x N dimensional array. It has one row/column for each variable. The diagonal elements are therefore, what? The variable variances! While the off-diagonal elements are what? The covariances! And those are the values you want to plot a histogram of. So keeping in mind that the covariance matrix is symmetric (upper triangle is the same as (i.e. transpose of) lower triangle), you simply should just get the upper (or lower) triangle values out into a list and put *those* values into the `plt.hist` function. [Here's a Stackoverflow question that addresses your problem](https://stackoverflow.com/questions/8905501/extract-upper-or-lower-triangular-part-of-a-numpy-matrix).

Cheers
