### ISSUE TITLE
Ex. 3.2.1

### ISSUE THREAD

**Issue by Avanderheyde** [ulfaslak/caobd_f19#5]
For 3.2.1 

I am trying to make a list with the length of each page for villains. 
When I loop through the list of villain names to retrieve the markups, the program stops after ~90 request and says:

HTTPSConnectionPool(host='en.wikipedia.org', port=443): Max retries exceeded with url: /w/api.php?format=json&action=query&prop=revisions&rvprop=content&titles=Brynocki (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))

I googled the error seems people get similar errors when they making too many requests and the website server cuts them off. Any suggests on how to get around this?

**Comment by ulfaslak** [comment]
I haven't seen this before. But I think it may be Wikimedia blocking your requests because you make too many. Try either changing your user agent in the `rq.get` with every call, or write your code such that you restart later and pick up where you left off (like not try to get character pages that you already accessed and saved). Let me know if this solves your problem.

**Comment by baileyheit** [comment]
I am also receiving this error. Can you give an example of what you mean by changing the user agent in the rq.get?

**Comment by ulfaslak** [comment]
In `request.get` you can change the header sent to the API. Something like this:

```Python
rq.get(link, headers={'User-agent': 'my custom UA'})
```

As said, I haven't seen the error before, so it's probably something new the MediaWiki API is doing to avoid too many requests. So I think you could avoid this error by changing the `headers={'User-agent': 'my custom UA'}` in every iteration. Just a guess though.
