### ISSUE TITLE
3.2.3 - getting debut years

### ISSUE THREAD

**Issue by Avanderheyde** [ulfaslak/caobd_f19#9]
import re

> i = "Spider-Man"
> character = rq.get("https://en.wikipedia.org/w/api.php?format=json&action=query&prop=revisions&rvprop=content&titles="+i,headers = {'User-agent': 'sneakybot'}).json()
> 
> markup_text = str(list(character['query']['pages'].values())[0]['revisions'][0]['*'])

### I can't seem to get this to work. 
> **re.findall(r"\d{4}\)", re.findall(r"debut.+?\n", markup_text)[0])[0][:-1]**

It says index out of range. debut_yr = re.findall(r"\d{4}\)", re.findall(r"debut.+?\n", markup_text)[0]) returns and empty list even when I know Spider-man does have debut year.

**Comment by ulfaslak** [comment]
That somehow also doesn't work for me with Spider-man regex also doesn't work for me. The error you get is caused by the list returned from `re.findall` being empty when you try to index it (it found nothing).

Here's another approach:

```Python
re.findall(r'debut.+?\d{4}', markup_text)[0][-4:]
```

This gets the first instance of a text string that starts with "debut" and ends with four digits (there could be many), then extracts the last four digits. Probably your year.
